// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Infraestructura.Data;

#nullable disable

namespace TaskManager.Infraestructura.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250107003819_CrearEntidadOrdenesProductosSuministradores")]
    partial class CrearEntidadOrdenesProductosSuministradores
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TaskManager.Dominio.Entidades.OrdenProductoSuministradorModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CantidadDeOrden")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraDeCreacion")
                        .HasColumnType("time");

                    b.Property<double>("PrecioTotal")
                        .HasColumnType("float");

                    b.Property<int>("ProductoSuministradorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoSuministradorId");

                    b.ToTable("OrdenesProductosSuministradores");
                });

            modelBuilder.Entity("TaskManager.Dominio.Entidades.ProductoSuministradorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CantidadProductoEnVenta")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaProductoSuministradorEnum")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrdenProductoSuministradorModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("PrecioProducto")
                        .HasColumnType("float");

                    b.Property<int>("SuministradorId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadProductoEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenProductoSuministradorModelId");

                    b.HasIndex("SuministradorId");

                    b.ToTable("ProductosSuministradores");
                });

            modelBuilder.Entity("TaskManager.Dominio.Entidades.ReservacionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoReservacionEnum")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechadeReservacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoradeReservacion")
                        .HasColumnType("time");

                    b.Property<int>("MesasEnum")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("TaskManager.Dominio.Entidades.SuministradorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DireccionLinea1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DireccionLinea2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProductoSuministradorModelId")
                        .HasColumnType("int");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoSuministradorModelId");

                    b.ToTable("Suministradores");
                });

            modelBuilder.Entity("TaskManager.Dominio.Entidades.OrdenProductoSuministradorModel", b =>
                {
                    b.HasOne("TaskManager.Dominio.Entidades.ProductoSuministradorModel", "ProductoSuministrador")
                        .WithMany()
                        .HasForeignKey("ProductoSuministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoSuministrador");
                });

            modelBuilder.Entity("TaskManager.Dominio.Entidades.ProductoSuministradorModel", b =>
                {
                    b.HasOne("TaskManager.Dominio.Entidades.OrdenProductoSuministradorModel", null)
                        .WithMany("Productos")
                        .HasForeignKey("OrdenProductoSuministradorModelId");

                    b.HasOne("TaskManager.Dominio.Entidades.SuministradorModel", "Suministrador")
                        .WithMany()
                        .HasForeignKey("SuministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suministrador");
                });

            modelBuilder.Entity("TaskManager.Dominio.Entidades.SuministradorModel", b =>
                {
                    b.HasOne("TaskManager.Dominio.Entidades.ProductoSuministradorModel", null)
                        .WithMany("SuministradorList")
                        .HasForeignKey("ProductoSuministradorModelId");
                });

            modelBuilder.Entity("TaskManager.Dominio.Entidades.OrdenProductoSuministradorModel", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("TaskManager.Dominio.Entidades.ProductoSuministradorModel", b =>
                {
                    b.Navigation("SuministradorList");
                });
#pragma warning restore 612, 618
        }
    }
}
